#!/usr/bin/env bash
# bootstrap.sh — onboard a new repo into the agent-standards system
#
# Usage:
#   ./scripts/bootstrap.sh <org/repo> "<Project Name>" "<Short description>"
#
# What it does:
#   1. Copies shared/06-agent-behavior.md → .context/06-agent-behavior.md in the target repo
#   2. Generates AGENTS.md, GEMINI.md, CODEX.md, HERMES.md from templates (with placeholders filled)
#   3. Opens a PR in the target repo
#
# Requirements:
#   - gh CLI authenticated with write access to the target repo
#   - Run from the root of the agent-standards repo

set -euo pipefail

REPO="${1:?Usage: $0 <org/repo> '<Project Name>' '<Description>'}"
PROJECT_NAME="${2:?missing project name}"
PROJECT_DESC="${3:?missing project description}"
BRANCH="chore/bootstrap-agent-context"
TMPDIR=$(mktemp -d)

echo "→ Bootstrapping agent context for $REPO"

# Clone target repo
gh repo clone "$REPO" "$TMPDIR/target" -- --depth=1 --quiet
cd "$TMPDIR/target"
git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"

# Copy shared behavior contract
mkdir -p .context
cp "$OLDPWD/shared/06-agent-behavior.md" .context/06-agent-behavior.md

# Generate agent files from templates
substitute() {
  sed \
    -e "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" \
    -e "s/{{PROJECT_DESCRIPTION}}/$PROJECT_DESC/g" \
    "$1"
}

substitute "$OLDPWD/templates/AGENTS.md.template"   > AGENTS.md
substitute "$OLDPWD/templates/GEMINI.md.template"   > GEMINI.md
substitute "$OLDPWD/templates/CODEX.md.template"    > CODEX.md
substitute "$OLDPWD/templates/HERMES.md.template"   > HERMES.md

# Commit and push
git add .context/06-agent-behavior.md AGENTS.md GEMINI.md CODEX.md HERMES.md
git commit -m "chore: bootstrap agent context from agent-standards

Adds shared behavior contract and agent index files.
Source: https://github.com/Recog-Omni/agent-standards"

git push origin "$BRANCH" --quiet

# Open PR
gh pr create \
  --title "chore: bootstrap agent context — $PROJECT_NAME" \
  --body "## Summary

Adds the shared AI agent behavior contract and index files from [Recog-Omni/agent-standards](https://github.com/Recog-Omni/agent-standards).

### Files added / updated
- \`.context/06-agent-behavior.md\` — shared behavior contract (senior engineer role, quality bar, definition of done)
- \`AGENTS.md\` — cross-tool agent index
- \`GEMINI.md\` — Gemini-specific index
- \`CODEX.md\` — Codex-specific index
- \`HERMES.md\` — Hermes-specific index

### Next steps
Fill in the \`<!-- PROJECT-SPECIFIC -->\` sections in each file with project build commands and gotchas.

🤖 Generated by [agent-standards/scripts/bootstrap.sh](https://github.com/Recog-Omni/agent-standards/blob/main/scripts/bootstrap.sh)" \
  --head "$BRANCH"

echo "✓ PR opened in $REPO"
cd /
rm -rf "$TMPDIR"
