#!/usr/bin/env bash
# bootstrap.sh — onboard a new repo into the agent-standards system
#
# Usage:
#   ./scripts/bootstrap.sh <org/repo> "<Project Name>" "<Short description>" [stack]
#
#   [stack] — optional; must match a file in shared/stacks/ (e.g. "kmp")
#
# What it does:
#   1. Copies shared/06-agent-behavior.md → .context/06-agent-behavior.md in the target repo
#      (plus shared/stacks/<stack>.md → .context/06-stack-<stack>.md when a stack is given)
#   2. Generates AGENTS.md (canonical contract), CLAUDE.md, GEMINI.md, HERMES.md, and
#      .github/copilot-instructions.md from templates (with placeholders filled)
#   3. Opens a PR in the target repo
#
# Requirements:
#   - gh CLI authenticated with write access to the target repo
#   - Run from the root of the agent-standards repo

set -euo pipefail

REPO="${1:?Usage: $0 <org/repo> '<Project Name>' '<Description>' [stack]}"
PROJECT_NAME="${2:?missing project name}"
PROJECT_DESC="${3:?missing project description}"
STACK="${4:-}"
BRANCH="chore/bootstrap-agent-context"
TMPDIR=$(mktemp -d)

if [ -n "$STACK" ] && [ ! -f "shared/stacks/$STACK.md" ]; then
  echo "✗ unknown stack '$STACK' — no shared/stacks/$STACK.md" >&2
  exit 1
fi

echo "→ Bootstrapping agent context for $REPO"

# Clone target repo
gh repo clone "$REPO" "$TMPDIR/target" -- --depth=1 --quiet
cd "$TMPDIR/target"
git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"

# Copy shared behavior contract (and stack contract if given)
mkdir -p .context .github
cp "$OLDPWD/shared/06-agent-behavior.md" .context/06-agent-behavior.md
if [ -n "$STACK" ]; then
  cp "$OLDPWD/shared/stacks/$STACK.md" ".context/06-stack-$STACK.md"
fi

# Generate agent files from templates
substitute() {
  sed \
    -e "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" \
    -e "s/{{PROJECT_DESCRIPTION}}/$PROJECT_DESC/g" \
    "$1"
}

substitute "$OLDPWD/templates/AGENTS.md.template"               > AGENTS.md
substitute "$OLDPWD/templates/CLAUDE.md.template"               > CLAUDE.md
substitute "$OLDPWD/templates/GEMINI.md.template"               > GEMINI.md
substitute "$OLDPWD/templates/HERMES.md.template"               > HERMES.md
substitute "$OLDPWD/templates/copilot-instructions.md.template" > .github/copilot-instructions.md

# Commit and push
git add .context/ AGENTS.md CLAUDE.md GEMINI.md HERMES.md .github/copilot-instructions.md
git commit -m "chore: bootstrap agent context from agent-standards

Adds shared behavior contract and agent index files.
Source: https://github.com/Recog-Omni/agent-standards"

git push origin "$BRANCH" --quiet

# Open PR
gh pr create \
  --title "chore: bootstrap agent context — $PROJECT_NAME" \
  --body "## Summary

Adds the shared AI agent behavior contract and index files from [Recog-Omni/agent-standards](https://github.com/Recog-Omni/agent-standards).

### Files added / updated
- \`.context/06-agent-behavior.md\` — shared behavior contract (senior engineer role, quality bar, issue workflow, definition of done)
- \`AGENTS.md\` — **canonical** cross-tool agent contract
- \`CLAUDE.md\` — thin Claude pointer (imports AGENTS.md)
- \`GEMINI.md\` / \`HERMES.md\` — thin tool pointers
- \`.github/copilot-instructions.md\` — Copilot inline rules + pointer

### Next steps
1. Fill in the \`<!-- PROJECT-SPECIFIC -->\` sections (verification commands, quick reference, gotchas)
2. Create the remaining \`.context/\` files (01–05, 07–08) for this project
3. Add the repo to \`projects.yml\` in agent-standards so future contract syncs include it

🤖 Generated by [agent-standards/scripts/bootstrap.sh](https://github.com/Recog-Omni/agent-standards/blob/main/scripts/bootstrap.sh)" \
  --head "$BRANCH"

echo "✓ PR opened in $REPO"
cd /
rm -rf "$TMPDIR"
